version: '3'

tasks:
  build:
    desc: "Build the tins binary"
    cmds:
      - go mod tidy
      - go build -o tins .

  create:
    desc: "Create a temporary instance (usage: task create -- <instance-name>)"
    cmds:
      - ./tins create {{.CLI_ARGS}}
    preconditions:
      - test -f ./tins
    silent: false

  list:
    desc: "List all temporary instances"
    cmds:
      - ./tins list
    preconditions:
      - test -f ./tins
    silent: false

  terminate:
    desc: "Terminate a temporary instance (usage: task terminate -- <instance-name-or-id>)"
    cmds:
      - ./tins terminate {{.CLI_ARGS}}
    preconditions:
      - test -f ./tins
    silent: false

  connect:
    desc: "Connect to a temporary instance via SSH (shows fzf menu if no instance specified)"
    cmds:
      - ./tins connect {{.CLI_ARGS}}
    preconditions:
      - test -f ./tins
    silent: false

  custom-create:
    desc: "Create a temporary instance with custom user-data"
    cmds:
      - ./tins create {{.CLI_ARGS}} --user-data testdata/user-data.sh
    preconditions:
      - test -f ./tins
      - test -f testdata/user-data.sh
    silent: false

  default:
    desc: "Show available tasks"
    cmds:
      - task --list
